### ISSUE TITLE
Fetching public data is broken .

### ISSUE THREAD

**Issue by SHAANBHAYA** [gameup-io/gameup-unity-sdk#49]
I am currently facing this issue where i cannot fetch the data marked as public read .
`
void ReadData()
{
if (_sessionClient != null) {
			String storageTable = "questions";
			String storageKey = "A000001";

			_sessionClient.DatastoreGet (storageTable,storageKey,(DatastoreObject dso) => {
				object q;
				dso.Data.TryGetValue("Questions",out q);
				Debug.Log ("Question=" + q);
			}, (status, reason) => {
				Debug.Log ("Not Able to fetch Questions "+status+". Reason= "+reason );
			});
		}
}`
Your documentation seems vague where you use the term global objects and public values are used interchangeably, or maybe i am wrong. There is no community support and you guys have not provided any example projects too,so can you help me debug as to what am i doing wrong.
Specifications below :- 

- Using Unity 4.61 
- Can write and delete data from the same owner as of now.
-Want to access public data from other users .
-Table name is questions,permissions :Public Read & Owner Write
-code has been provided above
-Log says cannot find the key

**Comment by novabyte** [comment]
@SHAANBHAYA Were you able to find what you needed?

> Want to access public data from other users

To access public data owned by other users you perform queries on the Datastore table with the table permissions set to public read.

> Your documentation seems vague where you use the term global objects and public values are used interchangeably, or maybe i am wrong.

We describe objects as global if they're owned by the system rather than a player. This is possible when the table is created with no write and owner read permissions. The only way the object can be created is via the dashboard or via Lua code with our Cloud Code runtime. This is perfect for configuration objects like version checks for game clients, etc.

A public object is one that is owned by a player but shared so it can be read by all players. You can have a look at our [Unity guide](https://heroiclabs.com/docs/guide/unity/#datastore) and the [concept documentation](https://heroiclabs.com/docs/concepts/datastore/#permissions) for more info. Let me know how I can help.
